CREATE SCHEMA IF NOT EXISTS INF_FILE;

CREATE TABLE IF NOT EXISTS INF_FILE.FILE_RESOURCE (
    ID BIGSERIAL PRIMARY KEY,
    RESOURCE_TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    URL TEXT,
    IS_URL_EXPIRABLE BOOLEAN NOT NULL DEFAULT FALSE,
    BUCKET_NAME VARCHAR(255) NOT NULL,
    OBJECT_PATH TEXT NOT NULL,
    PARENT_PATH TEXT,
    PATH_DEPTH INTEGER NOT NULL DEFAULT 0,
    PATH_1 VARCHAR(255),
    PATH_2 VARCHAR(255),
    PATH_3 VARCHAR(255),
    PATH_4 VARCHAR(255),
    PATH_5 VARCHAR(255),
    PATH_6 VARCHAR(255),
    PATH_7 VARCHAR(255),
    PATH_8 VARCHAR(255),
    PATH_9 VARCHAR(255),
    PATH_10 VARCHAR(255),
    EXTENSION VARCHAR(50),
    CONTENT_TYPE VARCHAR(255),
    FILE_SIZE BIGINT,
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_FILE_RESOURCE_OBJECT_PATH UNIQUE (OBJECT_PATH)
);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_NAME
    ON INF_FILE.FILE_RESOURCE (NAME);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PARENT_PATH
    ON INF_FILE.FILE_RESOURCE (PARENT_PATH);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_TYPE
    ON INF_FILE.FILE_RESOURCE (RESOURCE_TYPE);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_1
    ON INF_FILE.FILE_RESOURCE (PATH_1);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_2
    ON INF_FILE.FILE_RESOURCE (PATH_2);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_3
    ON INF_FILE.FILE_RESOURCE (PATH_3);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_4
    ON INF_FILE.FILE_RESOURCE (PATH_4);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_5
    ON INF_FILE.FILE_RESOURCE (PATH_5);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_6
    ON INF_FILE.FILE_RESOURCE (PATH_6);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_7
    ON INF_FILE.FILE_RESOURCE (PATH_7);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_8
    ON INF_FILE.FILE_RESOURCE (PATH_8);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_9
    ON INF_FILE.FILE_RESOURCE (PATH_9);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_10
    ON INF_FILE.FILE_RESOURCE (PATH_10);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_SEARCH
    ON INF_FILE.FILE_RESOURCE (PATH_1, PATH_2, PATH_3, PATH_4, PATH_5);

COMMENT ON TABLE INF_FILE.FILE_RESOURCE IS 'Metadata file/folder/object luu tren MinIO';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.NAME IS 'Ten file hoac folder hien tai';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.URL IS 'Relative URL khong co host/IP, vi du: /infinite-world/avatar/file.jpg';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.IS_URL_EXPIRABLE IS 'true: URL co han (presigned), false: URL vinh vien (permanent)';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.OBJECT_PATH IS 'Duong dan day du trong MinIO';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PARENT_PATH IS 'Duong dan folder cha truc tiep';
