server.port=8082
spring.application.name=i18n-service

# Load environment from .env.properties
spring.config.import=optional:file:.env.properties

# Database Configuration (PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# I18n Configuration
i18n.cache-prefix=i18n:
i18n.cache-expire-hours=24
i18n.languages=en,vi
i18n.default-language=en
i18n.properties-file=/i18n/messages

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=2000

# Logging
logging.level.root=INFO
logging.level.com.infinite=DEBUG

