services:
  # Gateway Service
  inf-gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: inf-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env_docker.properties
    networks:
      - infinite-network

  # User Service
  inf-user:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: inf-user
    ports:
      - "8081:8081"
      - "18081:18081"
    env_file:
      - .env_docker.properties
    networks:
      - infinite-network

  # I18N Service
  inf-i18n:
    build:
      context: .
      dockerfile: i18n/Dockerfile
    container_name: inf-i18n
    ports:
      - "8082:8082"
    env_file:
      - .env_docker.properties
    networks:
      - infinite-network
#
  # File Service
  inf-file:
    build:
      context: .
      dockerfile: file-service/Dockerfile
    container_name: inf-file
    ports:
      - "8083:8083"
      - "18083:18083"
    env_file:
      - .env_docker.properties
    networks:
      - infinite-network
#
  # Notification Service
  inf-notification:
    build:
      context: .
      dockerfile: notification/Dockerfile
    container_name: inf-notification
    ports:
      - "8084:8084"
    env_file:
      - .env_docker.properties
    networks:
      - infinite-network

networks:
  infinite-network:
    external: true