CREATE SCHEMA IF NOT EXISTS INF_FILE;

CREATE TABLE IF NOT EXISTS INF_FILE.FILE_RESOURCE (
    ID BIGSERIAL PRIMARY KEY,
    RESOURCE_TYPE VARCHAR(20) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    URL TEXT,
    BUCKET_NAME VARCHAR(255) NOT NULL,
    OBJECT_PATH TEXT NOT NULL,
    PARENT_PATH TEXT,
    PATH_DEPTH INTEGER NOT NULL DEFAULT 0,
    PATH_1 VARCHAR(255),
    PATH_2 VARCHAR(255),
    PATH_3 VARCHAR(255),
    PATH_4 VARCHAR(255),
    PATH_5 VARCHAR(255),
    PATH_6 VARCHAR(255),
    PATH_7 VARCHAR(255),
    PATH_8 VARCHAR(255),
    PATH_9 VARCHAR(255),
    PATH_10 VARCHAR(255),
    EXTENSION VARCHAR(50),
    CONTENT_TYPE VARCHAR(255),
    FILE_SIZE BIGINT,
    ETAG VARCHAR(255),
    VERSION_ID VARCHAR(255),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_FILE_RESOURCE_OBJECT_PATH UNIQUE (OBJECT_PATH),
    CONSTRAINT CK_FILE_RESOURCE_TYPE CHECK (RESOURCE_TYPE IN ('FILE', 'FOLDER', 'ZIP')),
    CONSTRAINT CK_FILE_RESOURCE_STATUS CHECK (STATUS IN ('ACTIVE', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_NAME
    ON INF_FILE.FILE_RESOURCE (NAME);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PARENT_PATH
    ON INF_FILE.FILE_RESOURCE (PARENT_PATH);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_STATUS
    ON INF_FILE.FILE_RESOURCE (STATUS);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_1
    ON INF_FILE.FILE_RESOURCE (PATH_1);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_2
    ON INF_FILE.FILE_RESOURCE (PATH_2);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_3
    ON INF_FILE.FILE_RESOURCE (PATH_3);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_4
    ON INF_FILE.FILE_RESOURCE (PATH_4);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_5
    ON INF_FILE.FILE_RESOURCE (PATH_5);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_6
    ON INF_FILE.FILE_RESOURCE (PATH_6);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_7
    ON INF_FILE.FILE_RESOURCE (PATH_7);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_8
    ON INF_FILE.FILE_RESOURCE (PATH_8);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_9
    ON INF_FILE.FILE_RESOURCE (PATH_9);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_10
    ON INF_FILE.FILE_RESOURCE (PATH_10);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_TYPE_STATUS
    ON INF_FILE.FILE_RESOURCE (RESOURCE_TYPE, STATUS);

CREATE INDEX IF NOT EXISTS IDX_FILE_RESOURCE_PATH_SEARCH
    ON INF_FILE.FILE_RESOURCE (PATH_1, PATH_2, PATH_3, PATH_4, PATH_5, STATUS);

COMMENT ON TABLE INF_FILE.FILE_RESOURCE IS 'Metadata file/folder/object luu tren MinIO';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.NAME IS 'Ten file/folder hien tai';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.URL IS 'Snapshot presigned URL, co the het han';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.OBJECT_PATH IS 'Duong dan day du trong MinIO';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PARENT_PATH IS 'Duong dan folder cha truc tiep';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_1 IS 'Cap folder 1';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_2 IS 'Cap folder 2';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_3 IS 'Cap folder 3';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_4 IS 'Cap folder 4';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_5 IS 'Cap folder 5';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_6 IS 'Cap folder 6';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_7 IS 'Cap folder 7';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_8 IS 'Cap folder 8';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_9 IS 'Cap folder 9';
COMMENT ON COLUMN INF_FILE.FILE_RESOURCE.PATH_10 IS 'Cap folder 10';

-- Mau insert file
INSERT INTO INF_FILE.FILE_RESOURCE (
    RESOURCE_TYPE,
    NAME,
    URL,
    BUCKET_NAME,
    OBJECT_PATH,
    PARENT_PATH,
    PATH_DEPTH,
    PATH_1,
    PATH_2,
    EXTENSION,
    CONTENT_TYPE,
    FILE_SIZE,
    STATUS,
    CREATED_BY,
    UPDATED_BY
) VALUES (
    'FILE',
    '20260426_013347_8cae9c69.jpg',
    'http://localhost:9000/infinite-world/avatar/20260426_013347_8cae9c69.jpg?...',
    'infinite-world',
    'infinite-world/avatar/20260426_013347_8cae9c69.jpg',
    'infinite-world/avatar',
    2,
    'infinite-world',
    'avatar',
    'jpg',
    'image/jpeg',
    102400,
    'ACTIVE',
    'system',
    'system'
);

-- Mau insert folder node
INSERT INTO INF_FILE.FILE_RESOURCE (
    RESOURCE_TYPE,
    NAME,
    BUCKET_NAME,
    OBJECT_PATH,
    PARENT_PATH,
    PATH_DEPTH,
    PATH_1,
    STATUS,
    CREATED_BY,
    UPDATED_BY
) VALUES (
    'FOLDER',
    'avatar',
    'infinite-world',
    'infinite-world/avatar',
    'infinite-world',
    1,
    'infinite-world',
    'ACTIVE',
    'system',
    'system'
)
ON CONFLICT (OBJECT_PATH) DO NOTHING;

-- 1. Get URL theo name
-- Neu co trung ten, can bo sung them PATH_1, PATH_2... de dinh danh dung.
SELECT
    ID,
    NAME,
    URL,
    OBJECT_PATH,
    RESOURCE_TYPE,
    STATUS
FROM INF_FILE.FILE_RESOURCE
WHERE STATUS = 'ACTIVE'
  AND NAME = '20260426_013347_8cae9c69.jpg';

-- 1b. Get URL theo name + filter cap 1, cap 2
SELECT
    ID,
    NAME,
    URL,
    OBJECT_PATH
FROM INF_FILE.FILE_RESOURCE
WHERE STATUS = 'ACTIVE'
  AND NAME = '20260426_013347_8cae9c69.jpg'
  AND PATH_1 = 'infinite-world'
  AND PATH_2 = 'avatar';

-- 2. Lay danh sach truc tiep ben trong folder
SELECT
    ID,
    NAME,
    RESOURCE_TYPE,
    OBJECT_PATH,
    URL,
    FILE_SIZE,
    CONTENT_TYPE
FROM INF_FILE.FILE_RESOURCE
WHERE STATUS = 'ACTIVE'
  AND PARENT_PATH = 'infinite-world/avatar'
ORDER BY
    CASE WHEN RESOURCE_TYPE = 'FOLDER' THEN 0 ELSE 1 END,
    NAME;

-- 3. Search theo cap 1
SELECT *
FROM INF_FILE.FILE_RESOURCE
WHERE STATUS = 'ACTIVE'
  AND PATH_1 = 'infinite-world'
ORDER BY OBJECT_PATH;

-- 4. Search theo cap 1 + cap 2
SELECT *
FROM INF_FILE.FILE_RESOURCE
WHERE STATUS = 'ACTIVE'
  AND PATH_1 = 'infinite-world'
  AND PATH_2 = 'avatar'
ORDER BY OBJECT_PATH;

-- 5. Search theo cap 1 + cap 2 + cap 3
SELECT *
FROM INF_FILE.FILE_RESOURCE
WHERE STATUS = 'ACTIVE'
  AND PATH_1 = 'infinite-world'
  AND PATH_2 = 'project'
  AND PATH_3 = 'a'
ORDER BY OBJECT_PATH;

-- 6. Search tong hop, co the dung cho native query voi tham so nullable
SELECT *
FROM INF_FILE.FILE_RESOURCE
WHERE STATUS = 'ACTIVE'
  AND (:path1 IS NULL OR PATH_1 = :path1)
  AND (:path2 IS NULL OR PATH_2 = :path2)
  AND (:path3 IS NULL OR PATH_3 = :path3)
  AND (:path4 IS NULL OR PATH_4 = :path4)
  AND (:path5 IS NULL OR PATH_5 = :path5)
  AND (:name IS NULL OR NAME = :name)
  AND (:resourceType IS NULL OR RESOURCE_TYPE = :resourceType)
ORDER BY OBJECT_PATH;

-- 7. Soft delete khi object da xoa khoi MinIO
UPDATE INF_FILE.FILE_RESOURCE
SET STATUS = 'DELETED',
    UPDATED_AT = CURRENT_TIMESTAMP,
    UPDATED_BY = 'system'
WHERE OBJECT_PATH = 'infinite-world/avatar/20260426_013347_8cae9c69.jpg';
