# Email Configuration - Hard coded values
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trungthanhvosong@gmail.com
spring.mail.password=bbbs emzf spgm kwfv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SMS Configuration
sms.provider.url=https://api.twilio.com/2010-04-01/Accounts
sms.provider.account-sid=
sms.provider.auth-token=
sms.provider.from-number=+1234567890
sms.mock.mode=true