services:

  infinite-game:
    build:
      context: .
      dockerfile: game-service/Dockerfile
    image: infinite-game:latest
    env_file:
      - .env.properties
    ports:
      - "8082:8082"
    networks:
      - infinite-net

networks:
  infinite-net:
    external: true
